# Site settings
title: Junyoung's Dev Days
name: JunYoung Oh # your name
email: plus4070@gmail.com # your email address
description: >
    A Simple Jekyll Blog Theme. # this means to ignore newlines until "baseurl:"
baseurl: "/plus4070.github.io" # the subpath of your site, e.g. /blog
url: "https://plus4070.github.io" # the base hostname & protocol for your site
twitter_username:  # your Twitter username
github_username: plus4070 # your Github username
disqus_username: plus4070 # your disqus username

google-analytics: UA-75034651-1 # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
